---
name: Release to crates.io

"on":
  workflow_dispatch:
    inputs:
      PACKAGE_NAME:
        required: false
        type: choice
        description: Publish only the selected package
        options:
        - ccnext-abi-encoding
        - ccnext-query-builder
  push:
    tags:
      - ccnext-abi-encoding-**
      - ccnext-query-builder-**

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  publish-from-manual-trigger:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/cargo-publish.yml
    with:
      package-name: ${{ inputs.PACKAGE_NAME }}
    secrets: inherit

  git-tag-sanity-check:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    outputs:
      PACKAGE_NAME: ${{ steps.identify-tag.outputs.PACKAGE_NAME }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Figure out tag name
        id: identify-tag
        shell: bash
        run: |
          TAG_NAME=$(git describe --tag)

          # WARNING: will fail when names change
          PACKAGE_NAME=$(echo "$TAG_NAME" | cut -f1-3 -d-)
          PACKAGE_VERSION=$(echo "$TAG_NAME" | cut -f4-99 -d-)

          echo "PACKAGE_NAME=$PACKAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> "$GITHUB_ENV"

          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - name: Check ${{ env.PACKAGE_VERSION }} vs Cargo.toml for ${{ env.PACKAGE_NAME }}
        working-directory: ${{ env.PACKAGE_NAME }}
        run: |
          grep "version = \"$PACKAGE_VERSION" Cargo.toml

  publish-from-git-tag:
    if: github.event_name == 'push'
    needs:
      - git-tag-sanity-check
    uses: ./.github/workflows/cargo-publish.yml
    with:
      package-name: ${{ needs.git-tag-sanity-check.outputs.PACKAGE_NAME }}
    secrets: inherit
