---
name: Release to crates.io

"on":
  workflow_dispatch:
    inputs:
      PACKAGE_NAME:
        required: false
        type: choice
        description: Publish only the selected package
        options:
        - ccnext-abi-encoding
        - ccnext-query-builder

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  cargo-publish:
    uses: ./.github/workflows/cargo-publish.yml
    with:
      package-name: ${{ inputs.PACKAGE_NAME }}
    secrets: inherit
