---
name: rust

"on":
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '**Cargo**'
      - '.github/workflows/rust.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  cargo-audit:
    if: github.base_ref == 'main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo audit
        run: |
          cargo install cargo-audit --features=fix --locked

      - name: Run cargo audit
        run: |
          cargo audit || true
          CC_MATCH=$(cargo audit --color never | grep -E "^.── creditcoin3-node" || true)

          # fail for anything which is a 1st level dependency of Creditcoin
          if [ -n "$CC_MATCH" ]; then
              echo "FAIL: Direct dependencies of Creditcoin found in audit report"
              echo "INFO: Inspect the output above for more information"
              exit 1
          else
              echo "INFO: No direct dependencies of Creditcoin found in audit report"
              exit 0
          fi

  cargo-fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        uses: gluwa/cargo@dev
        with:
          command: fmt
          args: -- --check

      - name: Check TOML formatting
        run: |
          cargo install taplo-cli --locked
          taplo format --check

  cargo-check:
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: Swatinem/rust-cache@v2

      - name: Check Build
        run: |
          cargo check --release

  cargo-clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy, rust-src
      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        uses: gluwa/cargo@dev
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  cargo-machete:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Execute cargo machete
        uses: bnjbvr/cargo-machete@main

  cargo-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: llvm-tools-preview, rust-src
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2.62.54
        with:
          tool: cargo-llvm-cov

      - name: Run tests
        run: |
          cargo llvm-cov \
              --release \
              --workspace --html --show-missing-lines --hide-instantiations \
              --ignore-filename-regex "(benchmarking.rs|mock.rs|tests(.*).rs|weights.rs)"

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: target/llvm-cov/html/
