---
name: Yank a crate from crates.io

"on":
  workflow_dispatch:
    inputs:
      PACKAGE_NAME:
        required: true
        type: choice
        description: Yank the selected package
        options:
        - ccnext-abi-encoding
        - ccnext-query-builder
      VERSION:
        required: true
        type: string
        description: Yank the selected version

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  cargo-yank:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Configure rustc version
        run: |
          RUSTC_VERSION=$(grep channel rust-toolchain.toml | tail -n1 | tr -d " " | cut -f2 -d'"')
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - uses: Swatinem/rust-cache@v2

      - name: Run cargo yank ${{ inputs.PACKAGE_NAME }}
        # NOTE: yank doesn't have a --package option like publish so call it
        # from inside the respective package directory
        working-directory: ${{ inputs.PACKAGE_NAME }}
        run: |
          cargo yank --verbose --version ${{ inputs.VERSION }} --token ${{ secrets.CRATES_IO_TOKEN }}
